services:
  - type: web
    name: ai-agency-strapi
    env: node
    region: frankfurt
    plan: free
    nodeVersion: 20.11.0
    buildCommand: mkdir -p public/uploads .tmp && npm install && NODE_ENV=production npm run build
    startCommand: NODE_ENV=production npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_wjW9Qm3rznMi@ep-gentle-boat-akgpn86y.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require
